PROJECT=KeraLua.iOS.sln
MDTOOL=/Applications/Xamarin\ Studio.app/Contents/MacOS/mdtool

all:
	#Make the iOS native library (remeber to update git submodules before run make)
	make -C "./external/lua/ios_build"
	cp "./external/lua/ios_build/libLua52iOS.a" src/libLua52iOS.a
	$(MDTOOL) build --target:Build --configuration:Release $(PROJECT)

clean:
	$(MDTOOL) build --target:Clean --configuration:Release $(PROJECT)
	rm -f *.a
	make -C "./external/lua/ios_build" clean
