PROJECT=KeraLua.Android.sln
MDTOOL=/Applications/Xamarin\ Studio.app/Contents/MacOS/mdtool

all:
	#Make the Android native library (remeber to update git submodules before run make)
	make -C "./external/lua/android_build"
	cp -r "./external/lua/android_build/libs" src/libs
	$(MDTOOL) build --target:Build --configuration:Release $(PROJECT)

clean:
	$(MDTOOL) build --target:Clean --configuration:Release $(PROJECT)
	rmdir -Rf src/libs
	make -C "./external/lua/ios_android" clean
