PROJECT=KeraLua.iOS.sln
MDTOOL=/Applications/MonoDevelop.app/Contents/MacOS/mdtool

all:
	$(MDTOOL) build --target:Build --configuration:Release $(PROJECT)

clean:
	$(MDTOOL) build --target:Clean --configuration:Release $(PROJECT)

